name: Connection Check

on:
  workflow_dispatch:

jobs:
  Login:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checking Development Environment  
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
